/**
 * @file bluetooth_core.c
 * @brief Bluetooth Core — FHSS, GFSK, BR/EDR Baseband, E0 Cipher (L2,L3,L5)
 *
 * Implements Bluetooth BR/EDR core algorithms:
 *   - Frequency Hop Selection Kernel
 *   - Gaussian Frequency Shift Keying (GFSK)
 *   - Adaptive Frequency Hopping (AFH)
 *   - Bluetooth packet construction (Access Code, HEC)
 *   - SCO/eSCO scheduling
 *   - E0 stream cipher
 *
 * Reference: Bluetooth Core Specification v5.4, Vol 2 "BR/EDR Controller"
 * Reference: Bray, J. & Sturman, C.F., "Bluetooth 1.1: Connect Without Cables",
 *            2nd ed., Prentice Hall, 2002.
 */

#include "bluetooth_core.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ==========================================================================
 * Frequency Hopping — Hop Selection (L2 Core Concept)
 * ========================================================================== */

int bt_fhss_init(bt_fhss_params_t *fhss, int region)
{
    if (!fhss) return -1;

    if (region == 0) {
        /* Worldwide: 79 channels, 2402-2480 MHz, 1 MHz spacing */
        fhss->n_channels        = 79;
        fhss->channel_spacing_mhz = 1.0;
    } else {
        /* France / reduced hop set: 23 channels */
        fhss->n_channels        = 23;
        fhss->channel_spacing_mhz = 1.0;
    }

    fhss->start_freq_mhz   = 2402.0;
    fhss->hop_rate_hz      = 1600;
    fhss->current_channel  = 0;
    fhss->hop_index        = 0;

    /* Initialize channel map: all channels good */
    memset(fhss->channel_map, 1, sizeof(fhss->channel_map));
    /* Mark channels beyond N_channels as unavailable */
    for (int i = fhss->n_channels; i < 79; i++) {
        fhss->channel_map[i] = 0;
    }

    /* Generate a default pseudo-random hop sequence */
    bt_address_t default_addr;
    memset(default_addr.addr, 0, 6);
    default_addr.addr[0] = 0x01;
    default_addr.addr[1] = 0x23;
    default_addr.addr[2] = 0x45;
    default_addr.addr[3] = 0x67;
    default_addr.addr[4] = 0x89;
    default_addr.addr[5] = 0xAB;
    bt_hop_sequence_generate(fhss->hop_sequence, 79, &default_addr);
    fhss->hop_seq_length = fhss->n_channels;

    return 0;
}

int bt_hop_select(int *channel, const bt_fhss_params_t *fhss,
                  const bt_clock_t *clk)
{
    if (!channel || !fhss || !clk) return -1;

    /* Phase = slot_number mod N_channels (with clock offset) */
    uint32_t phase = (clk->slot_number + (uint32_t)clk->clk_offset) % (uint32_t)fhss->n_channels;

    /* Select from hop sequence; skip bad channels via AFH remapping */
    int hop_ch = fhss->hop_sequence[phase % (uint32_t)fhss->hop_seq_length];

    /* If selected channel is bad (AFH), remap to nearest good channel */
    if (!fhss->channel_map[hop_ch]) {
        /* Scan forward for next good channel */
        int found = 0;
        for (int i = 1; i < fhss->n_channels && !found; i++) {
            int try_ch = (hop_ch + i) % fhss->n_channels;
            if (fhss->channel_map[try_ch]) {
                hop_ch = try_ch;
                found = 1;
            }
        }
        if (!found) {
            /* No good channels — catastrophic */
            return -1;
        }
    }

    *channel = hop_ch;
    return 0;
}

int bt_hop_sequence_generate(int *hop_sequence, int max_channels,
                             const bt_address_t *bd_addr)
{
    if (!hop_sequence || !bd_addr || max_channels < 79) return -1;

    int n_ch = 79;  /* Worldwide hop set */

    /* Bluetooth hop selection kernel uses the BD_ADDR to permute a
     * base sequence. The base sequence is a permutation of 0..n_ch-1.
     *
     * For the hopping kernel, the sequence is generated by:
     *   1. Initialize permutation with consecutive values
     *   2. Permute based on BD_ADDR LAP bits
     */

    /* Initialize with identity */
    for (int i = 0; i < n_ch; i++) {
        hop_sequence[i] = i;
    }

    /* Fisher-Yates shuffle using BD_ADDR as seed */
    uint32_t seed = ((uint32_t)bd_addr->addr[0] << 24) |
                    ((uint32_t)bd_addr->addr[1] << 16) |
                    ((uint32_t)bd_addr->addr[2] << 8)  |
                     (uint32_t)bd_addr->addr[3];
    uint32_t seed2 = ((uint32_t)bd_addr->addr[4] << 8) |
                      (uint32_t)bd_addr->addr[5];

    /* Simple RNG based on BD_ADDR */
    uint32_t state = seed ^ 0xDEADBEEF;
    for (int i = n_ch - 1; i > 0; i--) {
        /* Linear Congruential Generator: X_{n+1} = (a*X_n + c) mod m */
        state = state * 1103515245 + 12345 + seed2;
        int j = (int)(state % (uint32_t)(i + 1));

        /* Swap */
        int tmp = hop_sequence[i];
        hop_sequence[i] = hop_sequence[j];
        hop_sequence[j] = tmp;
    }

    return n_ch;
}

/* ==========================================================================
 * Adaptive Frequency Hopping (L2 Core Concept)
 * ========================================================================== */

int bt_afh_classify(bt_fhss_params_t *fhss, const double *per_channel,
                    int n_channels, double per_threshold)
{
    if (!fhss || !per_channel || n_channels <= 0) return -1;

    int good_count = 0;

    for (int i = 0; i < n_channels && i < fhss->n_channels; i++) {
        if (per_channel[i] > per_threshold) {
            fhss->channel_map[i] = 0;  /* Mark as bad */
        } else {
            fhss->channel_map[i] = 1;  /* Good channel */
            good_count++;
        }
    }

    /* Bluetooth requires at least 20 good channels (N_min = 20) */
    if (good_count < 20) {
        /* Not enough good channels — re-enable some bad channels */
        int need = 20 - good_count;
        /* Re-enable best (lowest PER) bad channels */
        /* Simplified: re-enable the first `need` bad channels scanned */
        for (int i = 0; i < n_channels && i < fhss->n_channels && need > 0; i++) {
            if (!fhss->channel_map[i]) {
                fhss->channel_map[i] = 1;
                need--;
                good_count++;
            }
        }
    }

    return good_count;
}

/* ==========================================================================
 * GFSK Modulation (L3 Mathematical Structure)
 * ========================================================================== */

/**
 * @brief Complementary error function approximation
 *
 * erfc(x) = 1 - erf(x) = 2/√π ∫_x^∞ e^{-t²} dt
 *
 * Uses Horner's method with coefficients from Abramowitz & Stegun 7.1.26.
 * Maximum error: 1.5×10⁻⁷
 *
 * @param x     Input value
 * @return erfc(x)
 */
static double my_erfc(double x)
{
    if (x < 0.0) return 2.0 - my_erfc(-x);

    double p = 0.3275911;
    double a1 = 0.254829592, a2 = -0.284496736, a3 = 1.421413741;
    double a4 = -1.453152027, a5 = 1.061405429;
    double t = 1.0 / (1.0 + p * x);
    double t2 = t * t;
    double poly = ((((a5 * t + a4) * t + a3) * t + a2) * t + a1) * t;
    return poly * exp(-x * x);
}

int bt_gfsk_init(bt_gfsk_params_t *gfsk, double bt_product,
                 double mod_index, double symbol_rate)
{
    if (!gfsk || bt_product <= 0.0 || mod_index <= 0.0 || symbol_rate <= 0.0) return -1;

    gfsk->bt_product       = bt_product;
    gfsk->modulation_index = mod_index;
    gfsk->symbol_rate_mbps = symbol_rate;

    /* Frequency deviation: Δf_peak = h / (2*T) = h * R_s / 2 */
    gfsk->frequency_dev_khz = mod_index * symbol_rate * 1000.0 / 2.0;

    /* Gaussian filter length: cover ~3 symbol periods on each side of peak */
    /* For BT=0.5, impulse response decays to <1% within ~2.5T */
    int len = (int)(6.0 / bt_product + 1.0);
    if (len < 8) len = 8;
    if (len > 32) len = 32;
    gfsk->gaussian_len = len;

    /* Allocate and compute GFSK pulse shape */
    gfsk->gfsk_pulse = (double *)malloc((size_t)len * sizeof(double));
    if (!gfsk->gfsk_pulse) return -1;

    /* GFSK pulse = convolution of Gaussian h(t) with rectangular pulse of width T_s
     *
     * g(t) = Q(2π·B·T·(t/T - 0.5) / √(ln 2)) - Q(2π·B·T·(t/T + 0.5) / √(ln 2))
     *
     * where Q(x) = ½·erfc(x/√2)
     *
     * B = BT / T  (3-dB bandwidth of Gaussian filter)
     * T = 1/R_s   (bit duration)
     */

    double T = 1.0 / (symbol_rate * 1e6);  /* Symbol period in seconds */
    double B = bt_product / T;              /* Filter bandwidth */
    double scale = 2.0 * M_PI * B * T / sqrt(log(2.0));  /* Pre-compute scaling factor */

    for (int i = 0; i < len; i++) {
        /* Evaluate at t = (i - len/2)·T/oversampling positions
         * For simplicity, sample the pulse at T_s resolution centered at 0 */
        double t = ((double)i - (double)(len - 1) / 2.0) * T;

        /* GFSK pulse: g(t) = ½[erfc(π√(2/ln2)·BT·(t/T - ½)) - erfc(π√(2/ln2)·BT·(t/T + ½))] */
        double arg1 = scale * (t / T - 0.5) / sqrt(2.0);
        double arg2 = scale * (t / T + 0.5) / sqrt(2.0);

        gfsk->gfsk_pulse[i] = 0.5 * (my_erfc(arg1) - my_erfc(arg2));
    }

    return 0;
}

int bt_gfsk_modulate(double *mod_samples, const uint8_t *bits, int n_bits,
                     int samples_per_symbol, const bt_gfsk_params_t *gfsk)
{
    if (!mod_samples || !bits || n_bits <= 0 || !gfsk) return -1;
    if (!gfsk->gfsk_pulse || samples_per_symbol <= 0) return -1;

    int pulse_len = gfsk->gaussian_len;
    int total_samples = n_bits * samples_per_symbol;

    /* Initialize output to zero */
    memset(mod_samples, 0, (size_t)total_samples * sizeof(double));

    /* For each bit, add its GFSK pulse contribution to the phase accumulator
     *
     * Phase(t) = π·h · Σ b[n] · ∫_{-∞}^{t} g(τ - nT) dτ
     *
     * The frequency deviation at time t is:
     *   Δf(t) = h/(2T) · Σ b[n] · g(t - nT)
     *
     * Phase accumulation:
     *   φ[k] = φ[k-1] + 2π · Δf[k] · Δt
     *
     * Complex baseband output: s[k] = exp(j·φ[k])
     */

    double T = 1.0 / (gfsk->symbol_rate_mbps * 1e6);
    double dt = T / (double)samples_per_symbol;
    double h = gfsk->modulation_index;

    /* Phase accumulator */
    double *phase = (double *)calloc((size_t)(total_samples + 1), sizeof(double));
    if (!phase) return -1;

    /* Compute frequency deviation for each sample (overlap-add of pulses) */
    double *freq_dev = (double *)calloc((size_t)total_samples, sizeof(double));
    if (!freq_dev) { free(phase); return -1; }

    for (int n = 0; n < n_bits; n++) {
        int bit_val = (bits[n] & 1) ? 1 : -1;  /* Map 1→+1, 0→-1 */
        int center_sample = n * samples_per_symbol + samples_per_symbol / 2;

        double peak_dev = h / (2.0 * T);  /* Peak frequency deviation in Hz */

        for (int pi = 0; pi < pulse_len; pi++) {
            int si = center_sample - pulse_len / 2 + pi;
            if (si >= 0 && si < total_samples) {
                freq_dev[si] += bit_val * peak_dev * gfsk->gfsk_pulse[pi];
            }
        }
    }

    /* Accumulate phase and generate IQ samples */
    for (int k = 0; k < total_samples; k++) {
        if (k > 0) {
            phase[k] = phase[k - 1] + 2.0 * M_PI * freq_dev[k - 1] * dt;
        }
        /* Normalize phase to [-π, +π] range */
        while (phase[k] > M_PI) phase[k] -= 2.0 * M_PI;
        while (phase[k] < -M_PI) phase[k] += 2.0 * M_PI;

        /* IQ output: interleaved I, Q */
        mod_samples[2 * k]     = cos(phase[k]);
        mod_samples[2 * k + 1] = sin(phase[k]);
    }

    free(phase);
    free(freq_dev);
    return total_samples;
}

int bt_gfsk_demodulate(uint8_t *decoded_bits, const double *iq_samples,
                       int n_iq, int samples_per_symbol,
                       const bt_gfsk_params_t *gfsk)
{
    if (!decoded_bits || !iq_samples || n_iq <= 0 || !gfsk) return -1;
    if (samples_per_symbol <= 0) return -1;

    /* Frequency discriminator demodulation:
     *   1. Compute phase: φ[k] = atan2(Q[k], I[k])
     *   2. Unwrap phase
     *   3. Differentiate: Δφ[k] = φ[k] - φ[k-1]
     *   4. Downsample to symbol rate: average/decimate
     *   5. Decide: Δφ > 0 → '1', Δφ < 0 → '0'
     */

    int n_symbols = n_iq / samples_per_symbol;
    if (n_symbols <= 0) return -1;

    /* Compute unwrapped phase */
    double *phase = (double *)malloc((size_t)n_iq * sizeof(double));
    if (!phase) return -1;

    for (int k = 0; k < n_iq; k++) {
        phase[k] = atan2(iq_samples[2 * k + 1], iq_samples[2 * k]);
    }

    /* Unwrap phase (remove 2π jumps) */
    for (int k = 1; k < n_iq; k++) {
        double diff = phase[k] - phase[k - 1];
        if (diff > M_PI) phase[k] -= 2.0 * M_PI;
        if (diff < -M_PI) phase[k] += 2.0 * M_PI;
    }

    /* Differentiate and downsample */
    for (int s = 0; s < n_symbols; s++) {
        int start = s * samples_per_symbol;
        int end   = (s + 1) * samples_per_symbol;
        if (end > n_iq) end = n_iq;

        /* Average frequency over symbol period */
        double sum_df = 0.0;
        for (int k = start + 1; k < end; k++) {
            sum_df += phase[k] - phase[k - 1];
        }

        /* Decision: positive frequency deviation → '1', negative → '0' */
        decoded_bits[s] = (sum_df > 0.0) ? 1 : 0;
    }

    free(phase);
    return n_symbols;
}

double bt_gfsk_eye_opening(const bt_gfsk_params_t *gfsk)
{
    if (!gfsk || !gfsk->gfsk_pulse) return 0.0;

    /* Eye opening at ideal sampling instant (center of pulse) */
    int center = gfsk->gaussian_len / 2;
    double peak = fabs(gfsk->gfsk_pulse[center]);

    /* Compute ISI from adjacent symbols (no worst-case pattern) */
    double isi = 0.0;
    for (int i = 0; i < gfsk->gaussian_len; i++) {
        if (i != center) {
            isi += fabs(gfsk->gfsk_pulse[i]);
        }
    }

    /* Eye opening ratio: peak / (peak + ISI) */
    return peak / (peak + isi);
}

/* ==========================================================================
 * Bluetooth Packet Construction (L2 Core Concept)
 * ========================================================================== */

/**
 * @brief Generate Bluetooth Device Access Code (DAC)
 *
 * The access code is derived from the master's LAP.
 * Sync word = BCH(64,30) encoding of LAP, followed by Barker sequence.
 *
 * Simplified: generate a 64-bit sync word pseudo-randomly from LAP.
 *
 * @param sync_word  Output 64-bit sync word (8 bytes)
 * @param lap        24-bit LAP value
 */
static void bt_sync_word_generate(uint8_t sync_word[8], uint32_t lap)
{
    /* Use a simplified BCH-like generation based on LAP */
    uint32_t code = lap ^ 0x00ABCD;  /* LAP-based initialization */

    for (int i = 0; i < 8; i++) {
        /* Simple LFSR-like expansion from LAP */
        code = code * 1103515245 + 12345;
        sync_word[i] = (uint8_t)((code >> 16) & 0xFF);
    }

    /* Barker-like preamble: first 4 bits should have good autocorrelation */
    sync_word[0] = (uint8_t)((sync_word[0] & 0xF0) | 0x0A);   /* 1010 preamble */
}

uint8_t bt_hec_compute(uint16_t header_word, uint8_t uap)
{
    /* HEC is an 8-bit CRC over 10 header bits + UAP
     *
     * Generator polynomial: D⁸ + D⁷ + D⁵ + D² + D + 1  = x⁸+x⁷+x⁵+x²+x+1
     *
     * The header word (10 bits) is shifted into an 8-bit CRC register
     * initialized with UAP. The CRC remainder is the HEC.
     */

    uint16_t data = header_word & 0x3FF;  /* 10 bits */
    uint16_t crc_val = (uint16_t)uap;      /* Initialized with UAP */

    /* Shift in 10 data bits */
    for (int i = 9; i >= 0; i--) {
        uint8_t bit_in = (uint8_t)((data >> i) & 1);
        uint8_t fb = (uint8_t)(((crc_val >> 7) & 1) ^ bit_in);
        crc_val = (uint16_t)(((crc_val << 1) & 0xFF) | fb);
        if (fb) {
            crc_val ^= 0x1A7;  /* Generator polynomial 0x1A7 = 110100111 */
            crc_val &= 0xFF;
        }
    }

    return (uint8_t)(crc_val & 0xFF);
}

int bt_packet_build(uint8_t *packet_buf, int max_len,
                    const bt_packet_t *pkt, const bt_address_t *bd_addr)
{
    if (!packet_buf || !pkt || !bd_addr || max_len < 10) return -1;

    /* Access Code (9 bytes = 72 bits): Preamble(4) + Sync Word(64) + Trailer(4)
     * In practice: 68 bits for non-FHS packets, 72 for FHS.
     */
    int offset = 0;

    /* Preamble: 4 bits (1010 or 0101 depending on LSB of sync word) */
    uint32_t lap = bt_address_get_lap(bd_addr);
    uint8_t sync_word[8];
    bt_sync_word_generate(sync_word, lap);

    /* Preamble: first bit of sync word determines polarity (0→0101, 1→1010) */
    uint8_t preamble = (sync_word[0] & 0x01) ? 0x0A : 0x05;
    packet_buf[offset++] = preamble & 0x0F;  /* Only low nibble */

    /* Sync word: 8 bytes */
    memcpy(packet_buf + offset, sync_word, 8);
    offset += 8;

    /* Trailer: 4 bits (same as last 4 bits of sync word extended) */
    /* For simplicity, skip trailer in buffer (access code = 68 effective bits) */

    /* Header: 54 bits ≈ 7 bytes
     * LT_ADDR(3) | Type(4) | Flow(1) | ARQN(1) | SEQN(1) | HEC(8) = 18 bits
     * Wait — the header is 54 bits including error correction (FEC 1/3 for DM)
     * Raw header = 18 bits → encoded to 54 for DM, 18 for DH.
     *
     * We store raw header (18 bits in low 3 bytes of a uint32_t)
     */
    uint32_t header_raw = ((uint32_t)(pkt->lt_addr & 0x07) << 15) |
                          ((uint32_t)(pkt->type & 0x0F) << 11) |
                          ((uint32_t)(pkt->flow & 0x01) << 10) |
                          ((uint32_t)(pkt->arqn & 0x01) << 9) |
                          ((uint32_t)(pkt->seqn & 0x01) << 8);

    uint8_t uap = bt_address_get_uap(bd_addr);
    uint8_t hec = bt_hec_compute((uint16_t)((header_raw >> 8) & 0x3FF), uap);
    header_raw |= (uint32_t)hec;  /* Low 8 bits = HEC */

    /* Store raw header in 3 bytes (MSB of 18-bit word first) */
    packet_buf[offset++] = (uint8_t)((header_raw >> 10) & 0xFF);  /* Actually 18 bits: bits 17-10 */
    packet_buf[offset++] = (uint8_t)((header_raw >> 2) & 0xFF);   /* bits 9-2 */
    packet_buf[offset++] = (uint8_t)((header_raw & 0x03) << 6);   /* bits 1-0, left-aligned in byte */
    /* 3 bytes = 24 bits, 18 bits used, 6 padding bits at end */

    /* Payload (if any) */
    if (pkt->payload && pkt->payload_len > 0) {
        int payload_space = max_len - offset - 2;  /* -2 for CRC-16 */
        int copy_len = (pkt->payload_len < payload_space) ? pkt->payload_len : payload_space;
        memcpy(packet_buf + offset, pkt->payload, (size_t)copy_len);
        offset += copy_len;

        /* CRC-16 for DM/DH packets if has_crc */
        if (pkt->has_crc) {
            /* Simple CRC-16 (not the full BT CRC, simplified checksum) */
            uint16_t crc = 0xFFFF;
            for (int i = 9; i < offset; i++) {  /* Start after access code */
                crc ^= (uint16_t)packet_buf[i] << 8;
                for (int b = 0; b < 8; b++) {
                    if (crc & 0x8000) crc = (uint16_t)((crc << 1) ^ 0x1021);
                    else crc = (uint16_t)(crc << 1);
                }
            }
            packet_buf[offset++] = (uint8_t)(crc >> 8);
            packet_buf[offset++] = (uint8_t)(crc & 0xFF);
        }
    }

    return offset;
}

int bt_packet_parse(bt_packet_t *pkt, const uint8_t *packet_buf, int packet_len)
{
    if (!pkt || !packet_buf || packet_len < 10) return -1;

    /* Access code: first 9 bytes (72 bits), skip */
    int offset = 9;
    if (packet_len <= offset) return -1;

    /* Header: next 3 bytes (18 bits raw)
     * bits: LT_ADDR(3) | Type(4) | Flow(1) | ARQN(1) | SEQN(1) | HEC(8)
     */
    uint32_t header_raw = ((uint32_t)packet_buf[offset] << 10) |
                          ((uint32_t)packet_buf[offset + 1] << 2) |
                          ((uint32_t)packet_buf[offset + 2] >> 6);
    offset += 3;

    pkt->lt_addr     = (uint8_t)((header_raw >> 15) & 0x07);
    pkt->type        = (bt_packet_type_t)((header_raw >> 11) & 0x0F);
    pkt->flow        = (uint8_t)((header_raw >> 10) & 0x01);
    pkt->arqn        = (uint8_t)((header_raw >> 9) & 0x01);
    pkt->seqn        = (uint8_t)((header_raw >> 8) & 0x01);

    /* HEC verification: re-compute and compare with received HEC */
    /* uint8_t rx_hec = (uint8_t)(header_raw & 0xFF); — verification done externally */
    (void)(header_raw & 0xFF);  /* HEC byte extracted from header */

    /* Payload: rest of the packet */
    int payload_len = packet_len - offset - 2;  /* -2 for CRC */
    if (payload_len > 0) {
        pkt->payload_len = payload_len;
        /* We cannot allocate memory here without knowing buffer ownership
         * so just set the pointer. Caller's responsibility. */
    } else {
        pkt->payload_len = 0;
    }

    /* CRC check: last 2 bytes */
    /* For a full implementation, would verify CRC-16 */

    return 0;
}

/* ==========================================================================
 * SCO Scheduling (L2 Core Concept)
 * ========================================================================== */

int bt_sco_schedule_init(bt_sco_schedule_t *sched, int tsco)
{
    if (!sched || tsco < 2 || (tsco & 1)) return -1;

    sched->tsco          = tsco;
    sched->dsco          = tsco - tsco / 2;  /* Offset: half of T_sco */
    sched->next_sco_slot = 0;
    sched->sco_count     = 1;

    return 0;
}

int bt_sco_is_reserved(const bt_sco_schedule_t *sched, uint32_t slot_num)
{
    if (!sched) return 0;

    /* SCO uses fixed periodic slots: reserved_slot = tsco * k + offset */
    int remainder = (int)(slot_num % (uint32_t)sched->tsco);
    /* Master-to-slave SCO: slot mod tsco == 0
     * Slave-to-master SCO: slot mod tsco == tsco/2 */
    /* Check if it's a master-to-slave SCO slot */
    if (remainder == 0) return 1;

    /* Check for slave SCO slot (if offset configured) */
    if (sched->dsco > 0 && remainder == sched->dsco) return 1;

    return 0;
}

/* ==========================================================================
 * E0 Stream Cipher (L5 Algorithm — Bluetooth BR/EDR)
 * ========================================================================== */

/** E0 LFSR state (4 LFSRs) */
static uint32_t e0_lfsr[4];
static int e0_initialized = 0;

/* LFSR tap masks */
#define E0_LFSR1_MASK  0x01200000  /* x²⁵ + x²⁰ + x¹² + x⁸ + 1 → taps at 25,20,12,8 (1-indexed bits) */
/* Actually implemented with polynomial masks below */

int bt_e0_init(const uint8_t key[16], const bt_address_t *bd_addr, uint32_t clk)
{
    if (!key || !bd_addr) return -1;

    /* Initialize LFSRs with key + BD_ADDR + clock-derived seed */

    /* LFSR1: 25 bits */
    e0_lfsr[0] = ((uint32_t)key[0] << 17) | ((uint32_t)key[1] << 9) | ((uint32_t)key[2] << 1) |
                 ((uint32_t)bd_addr->addr[0] >> 7);
    e0_lfsr[0] &= 0x01FFFFFF;

    /* LFSR2: 31 bits */
    e0_lfsr[1] = ((uint32_t)key[3] << 23) | ((uint32_t)key[4] << 15) | ((uint32_t)key[5] << 7) |
                 ((uint32_t)key[6] >> 1);
    e0_lfsr[1] &= 0x7FFFFFFF;

    /* LFSR3: 33 bits */
    e0_lfsr[2] = ((uint32_t)key[7] << 25) | ((uint32_t)key[8] << 17) | ((uint32_t)key[9] << 9) |
                 ((uint32_t)key[10] << 1) | ((uint32_t)bd_addr->addr[1] >> 7);
    e0_lfsr[2] &= 0x01FFFFFFFF;

    /* LFSR4: 39 bits */
    e0_lfsr[3] = ((uint32_t)key[11] << 27) | ((uint32_t)key[12] << 19) |
                 ((uint32_t)key[13] << 11) | ((uint32_t)key[14] << 3) |
                 ((uint32_t)key[15] >> 5);
    /* Upper part of 39-bit register (lower 32 + upper 7) */
    e0_lfsr[3] &= 0x7FFFFFFFFF;

    e0_initialized = 1;
    return 0;
}

/**
 * @brief Clock one LFSR
 *
 * @param reg      Pointer to LFSR value
 * @param mask     Feedback tap mask
 * @param n_bits   Number of bits in LFSR
 * @return Output bit
 */
static uint8_t e0_clock_lfsr(uint32_t *reg, uint32_t mask, int n_bits)
{
    /* XOR of tapped bits */
    uint32_t taps = *reg & mask;
    uint32_t fb = 0;
    while (taps) {
        fb ^= (taps & 1);
        taps >>= 1;
    }

    *reg = ((*reg << 1) | fb) & ((1UL << (uint32_t)n_bits) - 1);
    return (uint8_t)(*reg & 1);
}

int bt_e0_keystream(uint8_t *keystream, int n_bits)
{
    if (!keystream || n_bits < 1 || n_bits > 8) return -1;
    if (!e0_initialized) return -1;

    uint8_t ks = 0;

    for (int i = 0; i < n_bits; i++) {
        /* Clock each LFSR and XOR to get keystream bit */
        /* LFSR polynomials (feedback tap masks, excluding the xn term):
         * LFSR1: x²⁵ + x²⁰ + x¹² + x⁸ + 1 → feedback = d25 XOR d20 XOR d12 XOR d8
         * LFSR2: x³¹ + x²⁴ + x¹⁶ + x¹² + 1
         * LFSR3: x³³ + x²⁸ + x²⁴ + x⁴ + 1
         * LFSR4: x³⁹ + x³⁶ + x²⁸ + x⁴ + 1
         */

        /* Simplified: clock each LFSR using generic method */
        uint8_t b1 = e0_clock_lfsr(&e0_lfsr[0], 0x012000, 25);
        uint8_t b2 = e0_clock_lfsr(&e0_lfsr[1], 0x1000400, 31);
        uint8_t b3 = e0_clock_lfsr(&e0_lfsr[2], 0x10004000, 33);
        uint8_t b4 = e0_clock_lfsr(&e0_lfsr[3], 0x10004000, 39);  /* 39-bit LFSR mask */

        uint8_t bit = b1 ^ b2 ^ b3 ^ b4;
        ks = (uint8_t)((ks << 1) | bit);
    }

    *keystream = ks;
    return 0;
}

int bt_e0_crypt(uint8_t *output, const uint8_t *input, int n_bytes)
{
    if (!output || !input || n_bytes <= 0) return -1;
    if (!e0_initialized) return -1;

    for (int i = 0; i < n_bytes; i++) {
        uint8_t ks;
        bt_e0_keystream(&ks, 8);
        output[i] = input[i] ^ ks;
    }

    return 0;
}

/* ==========================================================================
 * RSSI / Link Quality (L2 Core Concept)
 * ========================================================================== */

double bt_rssi_to_distance(double rssi_dbm, double tx_power_dbm,
                           double path_loss_exp, double ref_loss_db)
{
    if (path_loss_exp <= 0.0) return -1.0;

    /* d = d₀ · 10^((P_tx - RSSI - PL(d₀)) / (10·n)) */
    double exponent = (tx_power_dbm - rssi_dbm - ref_loss_db) / (10.0 * path_loss_exp);
    return 1.0 * pow(10.0, exponent);  /* d₀ = 1 m */
}

int bt_link_quality(double rssi_dbm, double per, double noise_floor)
{
    /* Link Quality metric (0-255 per Bluetooth HCI specification)
     *
     * Based on RSSI, PER, and noise floor:
     *   - RSSI contributes 0-128 points
     *   - PER contributes 128-0 points (0% PER → 128, 100% → 0)
     *   - Noise margin contributes bonus
     */

    /* Map RSSI -90..-30 dBm → 0..128 */
    double rssi_score = (rssi_dbm + 90.0) * 128.0 / 60.0;
    if (rssi_score < 0.0) rssi_score = 0.0;
    if (rssi_score > 128.0) rssi_score = 128.0;

    /* Map PER 0.0..1.0 → 128..0 */
    double per_score = (1.0 - per) * 128.0;
    if (per_score < 0.0) per_score = 0.0;

    int lq = (int)(rssi_score + per_score);
    if (lq > 255) lq = 255;
    if (lq < 0) lq = 0;

    return lq;
}
